# Generated by Django 3.1.7 on 2021-03-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(error_messages={'unique': 'This email has already been registered.'}, max_length=100, unique=True),
        ),
    ]
