# Generated by Django 3.1.7 on 2021-03-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210302_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='college',
        ),
        migrations.DeleteModel(
            name='College',
        ),
    ]
